manics/jupyter-offlinenotebook

jupyter_offlinenotebook/static/main.js, setup.py
https://github.com/manics/jupyter-offlinenotebook/pull/4 made buttons conditional on the repo-id being found. This makes the download button always visible since it doesn't require local storage.
=> Always show client in-memory download button

jupyter_offlinenotebook/static/main.js
- Download as blob instead of base64 string to avoid size limits. Closes https://github.com/manics/jupyter-offlinenotebook/issues/3
- Trap localstorage exception (e.g. quota-exceeded) when saving (see https://github.com/manics/jupyter-offlinenotebook/issues/9)
=> Handle large notebooks

README.md, jupyter_offlinenotebook/static/main.js, setup.py
This hopefully avoids any unnecessary potential warnings about using local browser storage.
Also changes wording to `browser storage`.
=> Lazy load IndexedDB 

MANIFEST.in, setup.cfg, setup.py
The shipped license is BSD-3-clause, not MIT.
=> Fix License in setup.py; bundle in sdist and wheel

.travis.yml, binder/environment.yml, binder/postBuild
Builds were failing due to the source repo being cloned into `$HOME`. `jupyter labextension` then picked up some unrelated files such as `~/.cache` and ended up creating a circular symlink:
```
Yarn configuration loaded.
Node v10.19.0
> /usr/bin/npm pack /home/user
> jupyter-offlinenotebook@0.0.11 prepare /home/user
> jlpm run clean && jlpm run build
yarn run v1.15.2
$ rimraf lib tsconfig.tsbuildinfo
Done in 0.12s.
yarn run v1.15.2
$ tsc
Done in 3.38s.
npm notice 
npm notice 📦  jupyter-offlinenotebook@0.0.11
npm notice === Tarball Contents === 
npm notice 1.5kB   LICENSE                                       
npm notice 0       jupyter_offlinenotebook/static/style/index.css
npm notice 11.3kB  LICENSE.dexie                                 
npm notice 225.8kB lib/dexie.js …
```
=> Fix repo2docker/mybinder builds

.travis.yml, README.md, binder/postBuild, jupyter_offlinenotebook/static/jslib/index.ts, jupyter_offlinenotebook/static/jslib/offlinenotebook.d.ts, jupyter_offlinenotebook/static/style/index.css, package.json
Updates the lab extension for Jupyterlab 2.
Test this branch on mybinder: https://mybinder.org/v2/gh/manics/jupyter-offlinenotebook/jupyterlab2?urlpath=lab%2Ftree%2Fexample.ipynb
=> Update for Jupyterlab 2

dev-requirements.txt, tests/test_offlinenotebook.py
This ensures notebook releases will be tested.
In the latest `notebook` the title text may be different from the button label
=> Include notebook in dev-requirements.txt

.github/workflows/binder-badge.yaml
GitHub Actor is the user that opened the PR, but this may not be the same as the owner of the fork.
`pull_request.head.repo.full_name` should be the `owner/reponame` of the PR fork
=> Binder badge: use repo.full_name

tests/start.sh, tests/test_offlinenotebook.py
Attempt to fix a race condition where sometimes a dialog hasn't faded before an attempt at clicking a button is made. And a few other test cleanups.
=> Test fixes

.github/workflows/binder-badge.yaml
Use https://github.com/manics/action-binderbadge
This should be quieter than the current action since it will update an existing comment instead of creating a new one for every commit.
=> binder-badge use manics/action-binderbadge@main

.github/workflows/test.yml, .prettierignore, binder/environment.yml, binder/postBuild, dev-requirements.txt, package.json, pyproject.toml, setup.py
Bundles the JupyterLab 3 extension inside the python package, so there is no longer a need to build the extension.
JupyterLab 2 is unaffected, a build step is still required.
=> JupyterLab 3 pip installable

README.md
The instructions are out of date now that JupyterLab3 support is added in the master branch.
=> Update dev instructions in README

README.md, RELEASE.md, dev-requirements.txt, tests/test_offlinenotebook.py
Adds https://pypi.org/project/flaky/ to automatically rerun the JupyterLab 3 test that intermittently fails.
Updates the README to make JupyterLab more prominent.
=> Handle flaky JupyterLab 3 test, Update README

src/jslib/offlinenotebook.ts, tests/test_offlinenotebook.py
This ensures Firefox keeps the ipynb extension instead of overridding it to json
Closes https://github.com/manics/jupyter-offlinenotebook/issues/167
=> Set download type to application/x-ipynb+json

binder/environment.yml, dev-requirements-jl3.txt, tests/test_offlinenotebook.py, yarn.lock
Updates all JupyterLab deps in one go.
Also uses a temporary directory for JupyterLab's settings and workspaces which should ensure when tests are run they are not influenced by existing JupyterLab settings.
=> JupyterLab 3.2.4, update all JS deps

style/index.css
The current toolbar icon color is not themed. Therefore it does not have high contrast on dark theme:
This update the value to follow the toolbar icon theme of JupyterLab
=> Theme toolbar icon color

.github/workflows/build.yml, .pre-commit-config.yaml, dev-requirements-jl2.old, dev-requirements-jl3.txt, dev-requirements.txt, setup.py, tests/test_offlinenotebook.py
It's too difficult to get the Python 3.6/JupyterLab 2 tests working, so test Python 3.7+ and JupyterLab 3 only.
=> Update/fix CI, stop testing lab 2 / python 3.6

.github/workflows/build.yml, CHANGELOG.md, binder/environment.yml, package.json
Switches to PyPI trusted publisher (unfortunately NPM doesn't support that)
=>  Release candidate 0.3.0-rc.1

.github/workflows/build.yml, .gitpod.yml, MANIFEST.in, dev-requirements.txt, pyproject.toml, setup.py
This should ensure all files are included in the sdist, and that a wheel can be built from the sdist
See https://github.com/conda-forge/jupyter-offlinenotebook-feedstock/pull/6#issuecomment-1937789406
=> Use setuptools-scm to include files in sdist, switch to `python -mbuild`

.github/dependabot.yml
dependabot should still open NPM security updates
=> Disable NPM in dependabot, add github actions

package.json, src/index.ts, tests/test_offlinenotebook.py, tsconfig.json, yarn.lock
Fixes https://github.com/manics/jupyter-offlinenotebook/issues/645
=> Fix missing JupyterHub XSRF in config request
