manics/jupyter-offlinenotebook

jupyter_offlinenotebook/static/main.js

Closes https://github.com/manics/jupyter-offlinenotebook/issues/2

Show dialogs on save/load

---

jupyter_offlinenotebook/__init__.py
jupyter_offlinenotebook/static/main.js
setup.py

Add Binder link buttons for source repo and to the binder.
See:
- https://github.com/jupyterhub/mybinder.org-deploy/pull/1202
- https://github.com/jupyterhub/mybinder.org-deploy/pull/1284

Binder buttons

---

README.md
jupyter_offlinenotebook/__init__.py
setup.py

Make all binder and repository lookups configurable as callable.

Configuraiton properties are callable

---

jupyter_offlinenotebook/static/main.js

- Repo button opens link in new window
- Binder button displays URL and shows a copy button

Update Binder buttons

---

jupyter_offlinenotebook/static/main.js

Improve formatting of dialog. Loading now requires confirmation.

---

.travis.yml
MANIFEST.in
README.md
package.json
setup.py

Get the version from `package.json`.
Publish tagged releases to pypi and NPM.

Shared version for notebook and lab extensions

---

jupyter_offlinenotebook/static/jslib/index.ts
tsconfig.json

- The repo link button includes the repo label
- The binder link dialog includes a copy button

Jupyterlab buttons

---

.travis.yml
README.md
dev-requirements.txt
tests/start.sh
tests/test_offlinenotebook.py

Closes https://github.com/manics/jupyter-offlinenotebook/issues/12

Selenium tests

---

.travis.yml

https://github.com/mozilla/geckodriver/releases/tag/v0.27.0

Update geckodriver to 0.27.0

---

binder/postBuild

No need to upgrade jupyterlab in binder config.

Binder includes jupyterlab 2

---

.github/workflows/binder-badge.yaml

https://github.com/jupyterhub/binder/blob/76041518b7e39a6f4c48ab4190e4edf49da9bbed/doc/howto/binder-badge.yaml

Add workflow to comment on PRs with binder badge

---

.pre-commit-config.yaml
jupyter_offlinenotebook/__init__.py
setup.py
tests/test_offlinenotebook.py

Use black formatter.
No code changes, this is the result of running `pre-commit run -a`

Add black to pre-commit

---

binder/environment.yml
dev-requirements-jl3.txt
package.json
pyproject.toml
yarn.lock

jupyterlab 3.0.0rc10

---

binder/environment.yml
dev-requirements-jl3.txt
package.json
pyproject.toml
yarn.lock

JupyterLab 3.0.0 was released!

JupyterLab 3.0.0

---

.github/workflows/build.yml
README.md
RELEASE.md

Also updates the job to use a packed artefact for JupyterLab 2 instead of rebuilding the package.

Fix npm publish job

---

binder/environment.yml
dev-requirements-jl3.txt
yarn.lock

JupyterLab 3.0.3 and other JS bumps

JupyterLab 3.0.3

---

README.md
RELEASE.md
example.ipynb
tests/start.sh
tests/test_offlinenotebook.py

Update docs and other references to `master` branch

Replace master with main

---

binder/environment.yml
binder/postBuild
dev-requirements-jl3.txt
yarn.lock

Update JupyterLab and other yarn.lock packages.

jupyterlab==3.0.9

---

binder/environment.yml
dev-requirements-jl3.txt
src/index.ts
yarn.lock

JupyterLab 3.0.16

---

binder/environment.yml
dev-requirements-jl3.txt
yarn.lock

JupyterLab 3.1.0

---

binder/environment.yml
dev-requirements-jl3.txt
dev-requirements.txt
yarn.lock

`yarn.lock` was regenerated by:
```
rm yarn.lock
jlpm
```

Update dev/build dependencies

---

.pre-commit-config.yaml

Update .pre-commit-config.yaml versions

---

jupyter_offlinenotebook/__init__.py

https://jupyter-server.readthedocs.io/en/latest/developers/extensions.html#making-an-extensionapp-discoverable

Add _jupyter_server_extension_points

---

CHANGELOG.md
package.json

Should fix the missing source files in 0.3.0

Release 0.3.1-rc.1
